#!/bin/bash -e

DOMAIN=$(hostname --fqdn)
OUTDIR=/etc/ssl/certs

source /opt/letsencrypt/bin/activate
source /opt/letsencrypt/etc/lexicon-secrets.sh

exec dehydrated --cron \
	--hook /opt/letsencrypt/bin/lexicon-hook.sh \
	--challenge dns-01 \
	--domain $DOMAIN \
	--out $OUTDIR
